name: 知识图谱更新
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须授权写入权限
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 必须获取完整历史

      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 生成图谱数据
        run: |
          pip install regex
          python .github/scripts/generate_graph.py
          mv graph.json docs/

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # 与Secret名称一致
          publish_dir: ./docs
          keep_files: true
          allow_empty_commit: true # 允许空提交
