name: 知识图谱更新
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 生成图谱数据
        run: |
          pip install regex
          python .github/scripts/generate_graph.py
          mv graph.json docs/  # 将数据文件移动到docs目录

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
